### ISSUE TITLE
Bring back "Polygon" option in Box2d Physics

### ISSUE THREAD

**Issue by kachbit** [TurboWarp/extensions#1139] opened 2023-11-12 05:57 UTC
![](https://user-images.githubusercontent.com/57010635/203447777-d2469c21-77ba-4b5f-ab81-817c0beac399.png)

is there a possibility that this feature will be added back into the Box2d turbowarp extension? According to [this issue](https://github.com/TurboWarp/extensions/issues/42), replacing the removed API is relatively simple.

**Comment by CST1229** [comment] 2023-11-12 13:03
Also read the other part of the comment:
> but even in https://griffpatch.github.io/scratch-gui/ polygon mode is rather buggy

**Comment by kachbit** [comment] 2023-11-12 21:54
right but why not just bring it back and it will be optional

**Comment by kachbit** [comment] 2023-11-12 21:56
or do you know of a .js exention file for Box2d with the feature so that I can use it personally?

**Comment by GarboMuffin** [comment] 2023-11-15 05:43
I am closing this as a duplicate of the issue linked above

**Closed by GarboMuffin** 2023-11-15 05:43 UTC

**Comment by GarboMuffin** [comment] 2026-05-24 01:35
It's back
