### ISSUE TITLE
Add a discord rich presence to packaged project

### ISSUE THREAD

**Issue by Forysium** [TurboWarp/extensions#275] opened 2023-03-13 16:05 UTC
Hello guys,
i found a game made and packaged with turbowarp, that somehow managed to add a discord rich presence.
How is this possible? It was packaged with electron. Is there any extension out there that can do this?

**Comment by GarboMuffin** [comment] 2023-03-13 17:02
ask the person who made that project how they did it and consider sharing it here for everyone else to read

closing as a duplicate of https://github.com/TurboWarp/extensions/issues/220

**Closed by GarboMuffin** 2023-03-13 17:02 UTC

**Comment by Azulcat** [comment] 2023-07-30 15:01
@Forysium what is the game?
