### ISSUE TITLE
Thread Variables doesn't properly support recusing custom blocks 

### ISSUE THREAD

**Issue by snowboyz0825** [TurboWarp/extensions#1791] opened 2024-12-19 20:28 UTC
This is hyper-specific and may actually be intended, although I don't think it would make much sense I could see why. I was trying to set up something to copy a whole directory in the zip extension. (if there's an easier way to do it and have it overwrite and copy everything let me know, I tried a few things and it didn't seem to get everything for some reason. I decided to code my own thing.) Recursion (in my mind) seems to be the only way to properly get it to copy directories in directories and stuff, so I tried to set that up. (Keep in mind this is a modified version to try and see what's wrong). 

![block_12_19_2024-12_28_35 PM](https://github.com/user-attachments/assets/4a19b6fa-c94e-4400-a913-5c1f5effb0cd)
This, in theory, should recursively copy (just) directories and keep going further down into the folder structure. The boolean simply to log what happens to the original and not the recursors (?). If we run it with this simple setup,  
![Screenshot 2024-12-19 12 16 35 PM](https://github.com/user-attachments/assets/9e44191a-c0b9-4f94-b3dd-355d5a42534a)
![Screenshot 2024-12-19 12 16 04 PM](https://github.com/user-attachments/assets/06f41513-18c3-4f83-b474-8f008b95aa37)
![Screenshot 2024-12-19 12 17 08 PM](https://github.com/user-attachments/assets/c1b0b19e-3b25-4b80-a8e9-f117cafdde01)
It should copy the folders "1" and "2" from "test" into "test2". If we run it, we end up getting the result 
![Screenshot 2024-12-19 12 18 37 PM](https://github.com/user-attachments/assets/311b3a06-d9f6-434a-800f-9c02b68e859a)
Which is obviously not what is supposed to happen. The log (which logs what the thread variable should be for the original and only the original loop) reads
![Screenshot 2024-12-19 12 19 35 PM](https://github.com/user-attachments/assets/465c9777-5112-46aa-ae1a-f8d0577a3718)
This means that it tried to copy the first directory and then the first directory again. This was because it copies the first directory in the list, then searches then sets the thread variable "I" to zero to begin a search. There is absolutely nothing in this directory, so the recursor (?) ends up doing nothing but setting "I" to zero. The recursor finishes and the original block attempts to change "i" by one, causing it to do the same thing. It does not end up in a loop because the original block only tries to recurse (?) twice - once for every directory. 
If we run the same test but add a third folder, these are the results
![Screenshot 2024-12-19 12 25 29 PM](https://github.com/user-attachments/assets/789c6f50-301d-4320-83dc-b6ad77d63d8e)
![Screenshot 2024-12-19 12 25 22 PM](https://github.com/user-attachments/assets/f9ac60bb-08ef-4f53-99e3-87e80e774926)
which I believe adequately proves my point. I believe that logically and intuitively this should not work the way that it does, and they should be separate per block. 
In case anyone is curious, the solution to this is relatively simple - have the thread variable be separate for each recurse (?). They have an input so you could rig a system where two are never named the same thing for sure, though this is counter intuitive and clunky. What I ended up doing was setting the thread variable to the first input (which would be the path it is copying from.) Because it uses the whole path this should never overlap with another thread variable, though this solution is clunky and makes it annoying to code around. 

Sorry for the essay, and if this is intended behavior, once again, sorry.

**Comment by snowboyz0825** [comment] 2024-12-19 20:32
For further unneeded evidence, if we remove the recursing (?) and have it simply copy a single folder's directories, it works perfectly fine. 
![block_12_19_2024-12_31_33 PM](https://github.com/user-attachments/assets/50331d5a-6010-44ea-aff4-90087fe2e5d4)
![Screenshot 2024-12-19 12 32 03 PM](https://github.com/user-attachments/assets/290d008b-fb0e-42bb-88ee-1b2ce46e4c6e)
![Screenshot 2024-12-19 12 31 56 PM](https://github.com/user-attachments/assets/1d104391-4c21-451d-8d16-8dca63e93acc)

**Comment by CST1229** [comment] 2024-12-20 05:16
> Sorry for the essay, and if this is intended behavior, once again, sorry.

this *is* intended behavior, though it is kinda limiting. thread variables are scoped to threads, not scopes.

though see also: https://github.com/TurboWarp/extensions/pull/1026

**Comment by SharkPool-SP** [comment] 2024-12-22 05:24
Closing as its intentional

**Closed** 2024-12-22 05:24 UTC
