### ISSUE TITLE
sound.js: Sound (extension) doesn't work with Sound (Scratch) when packaged

### ISSUE THREAD

**Issue by DenisKincses** [TurboWarp/extensions#175] opened 2023-01-29 20:56 UTC
Just recently found this out, I was trying to use the pitch and the volumes from the Sound (Scratch) with the Sound (extension) when packaged, but it didn't do anything. 

Don't really know what the cause is, since I checked in the editor and it works perfectly fine.

**Comment by TheShovel** [comment] 2023-01-29 21:01
Does packaging it with electron work?
Also, what operating system are you on. Are you using the desktop app or the broswer version? And if you are packaging to html single file, then what browser are you opening the file on?

**Comment by DenisKincses** [comment] 2023-01-29 22:09
> Does packaging it with electron work? Also, what operating system are you on. Are you using the desktop app or the broswer version? And if you are packaging to html single file, then what browser are you opening the file on?

Sorry for not responding quicker, I'm using Windows 10 21H2, packaged to HTML single file, using the Desktop app of Turbowarp, and using Brave as the browser.

I had my friend test it out on his computer, he uses Windows 10, Opera GX. He had the same issue as me.

**Comment by TheShovel** [comment] 2023-01-29 22:11
Try packaging it with electron.

**Comment by DenisKincses** [comment] 2023-01-29 22:13
Will try that

**Comment by TheShovel** [comment] 2023-01-29 22:17
Also, on the html build, open the console, and show a screenshot of the logs.

**Comment by DenisKincses** [comment] 2023-01-29 22:24
![image](https://user-images.githubusercontent.com/78603495/215358884-f43ec653-8ba4-4aa9-9e76-55d475c13bc1.png)
HTML

on electron works perfectly fine

**Comment by DenisKincses** [comment] 2023-01-29 22:25
it does play the file in HTML, but whatever reason it's an error

**Comment by TheShovel** [comment] 2023-01-29 22:28
Because you put a local adress on it. Web pages can't access local files without a prompt. Upload the sounds to a website and use the link, or put them in the same folder as the html file. If you share your project without doing this, other people won't be able to hear the sound.

**Comment by DenisKincses** [comment] 2023-01-29 22:29
yeah but i made it so that you could put your own music in the project with a local address

**Comment by DenisKincses** [comment] 2023-01-29 22:30
also i couldn't even share this project because it's using custom extensions that Scratch doesn't support

**Comment by TheShovel** [comment] 2023-01-29 22:33
By share, I mean share the html file with others, also, this will be fixed with #173 , using the files extension. GarboMuffin has to approve the code first, so you'll have yo wait.

**Comment by DenisKincses** [comment] 2023-01-29 22:36
oh i see, well i will be sticking with electron until the files extensions will be released

**Comment by softedco** [comment] 2023-01-30 01:47
It looks like your sound can't be loaded into scratch's sound engine properly, if that happens it loads as a standart audio object which can't access scratch's advanced sound options

**Comment by TheShovel** [comment] 2023-01-30 08:00
And that is caused by what I mentioned.

**Comment by TheAwesome98-Real** [comment] 2023-02-04 08:46
#173 was merged

**Comment by softedco** [comment] 2023-02-04 08:51
> #173 was merged

As far as I can tell #173 is mostly not related to this

**Comment by TheAwesome98-Real** [comment] 2023-02-04 08:54
> > #173 was merged
> 
> As far as I can tell #173 is mostly not related to this

read this:

> By share, I mean share the html file with others, also, this will be fixed with #173 , using the files extension. GarboMuffin has to approve the code first, so you'll have to wait.

**Comment by TheShovel** [comment] 2023-02-04 12:08
It is related, and you can just load the new file extension now, and use that to get the music file from your pc.
This issue can be closed.

**Comment by softedco** [comment] 2023-02-04 13:02
> It is related, and you can just load the new file extension now, and use that to get the music file from your pc.
> This issue can be closed.

Am I missing something or what you're saying is that the user would need to manually load the sounds via the files extension each time so this doesn't occur. I don't think the issue is about this since you could get sound data uri easily enough before that.

**Comment by TheAwesome98-Real** [comment] 2023-02-04 13:45
it's probably easier since they can pick the file instead of writing the path

**Comment by softedco** [comment] 2023-02-04 13:57
> it's probably easier since they can pick the file instead of writing the path

I'm talking about the fact that you would have to pick the file each time manually, and you don't even need to do that since you can just convert the file to data uri and store it in a variable, which was possible before #173. The issue is about the sound not working with the html build but working with other builds like electron or in the editor, as I'm assuming by the title

**Comment by TheShovel** [comment] 2023-02-04 14:15
> > It is related, and you can just load the new file extension now, and use that to get the music file from your pc.
> > This issue can be closed.
> 
> Am I missing something or what you're saying is that the user would need to manually load the sounds via the files extension each time so this doesn't occur? I don't think the issue is about this since you could get sound data uri easily enough before that.

You are not getting what this issue was created for at all. OP wants to let users open a file FROM the project and the issue was that they were using a local address outside of the html file folder, so it didn't work. The new files updated fixes that by letting you pick FROM the project and returning a data uri. The sound is played correctly. Read the error here.
![image](https://user-images.githubusercontent.com/68913917/216772345-fccec902-49e1-4a44-a17a-f99e76cd37c2.png)

**Comment by TheShovel** [comment] 2023-02-04 14:16
Also read what the error means here
https://cloud.google.com/apigee/docs/api-platform/reference/policies/cors-policy#:~:text=Cross%2Dorigin%20resource%20sharing%20(CORS,is%20enforced%20by%20all%20browsers.

**Comment by softedco** [comment] 2023-02-04 14:53
> > > It is related, and you can just load the new file extension now, and use that to get the music file from your pc.
> > > This issue can be closed.
> > 
> > Am I missing something or what you're saying is that the user would need to manually load the sounds via the files extension each time so this doesn't occur? I don't think the issue is about this since you could get sound data uri easily enough before that.
> 
> You are not getting what this issue was created for at all. OP wants to let users open a file FROM the project and the issue was that they were using a local address outside of the html file folder, so it didn't work. The new files updated fixes that by letting you pick FROM the project and returning a data uri. The sound is played correctly. Read the error here.
> ![image](https://user-images.githubusercontent.com/68913917/216772345-fccec902-49e1-4a44-a17a-f99e76cd37c2.png)
> 
> 

You are not getting what I'm trying to say, what I'm trying to say is that you could do all that before the files extension was updated, and you don't even need it because it only allows for manual file loading and can't load files on itself, thus not actually resolving the issue. The issue is about sound not working in the standalone html build but working when using electron and in the editor.
I've seen the CORS error and I just need to clarify if the OP is using the desktop editor or the web version, if it's turbowarp desktop then the issue is resolved due to the fact that most browsers don't allow html to open files, but it is allowed in tw desktop and the electon build because they are not opened via browser. If it's the web turbowarp and it works there, then it is a browser that allows opening files, and the html build not working is actually a bug, either the extension's or the packager's, to fix which we'll need to ask garbomuffin.

**Comment by GarboMuffin** [comment] 2023-02-26 01:11
Projects being able to read projects from file:// was never intended. If you think it should be, open a new issue

**Closed by GarboMuffin** 2023-02-26 01:11 UTC
