### ISSUE TITLE
Can TurboWarp extensions be made in Chinese?

### ISSUE THREAD

**Issue by qxsck** [TurboWarp/extensions#278] opened 2023-03-18 04:29 UTC
Can TurboWarp extensions be made in Chinese?

**Comment by LukeManiaStudioss** [comment] 2023-03-18 13:26
What do you mean by this? Do you mean they can be translated into Chinese to allow for better accessibility?

**Comment by softedco** [comment] 2023-03-18 13:32
Custom extensions are currently not available for translation

**Comment by GarboMuffin** [comment] 2023-03-18 19:34
Closing as a duplicate of https://github.com/TurboWarp/extensions/issues/278

**Closed by GarboMuffin** 2023-03-18 19:34 UTC

**Comment by CST1229** [comment] 2023-03-18 20:07
...this is #278

**Comment by GarboMuffin** [comment] 2023-03-18 20:10
... as a duplicate of https://github.com/TurboWarp/extensions/issues/195

**Comment by qxsck** [comment] 2023-03-24 08:09
> What do you mean by this? Do you mean they can be translated into Chinese to allow for better accessibility?

Emm, I mean the expanded block text is in Chinese.

**Comment by Mickmick2012** [comment] 2023-03-24 08:38
i think he meant that the text is in Chinese only (no english), in that case, no, english is the language that most user knows

**Comment by True-Fantom** [comment] 2023-03-24 10:11
@qxsck @Mickmick2012 You can make an extension ONLY in Chinese, but as a personal extension (it will not be posted on the site)
