### ISSUE TITLE
Extension bug

### ISSUE THREAD

**Issue by TONYflare123** [TurboWarp/extensions#394] opened 2023-05-09 09:10 UTC
_Originally posted by @DT-is-not-available in https://github.com/TurboWarp/extensions/issues/207#issuecomment-1459068146_

Pen extension does not work beyond the actual stage, please fix that

**Comment by DT-is-not-available** [comment] 2023-05-09 19:18
Not sure how I would, the pen layer and texture is the size of the stage. I'll look into this nonetheless.

**Comment by Scratchfangs** [comment] 2023-05-11 00:55
Duplicate of https://github.com/TurboWarp/extensions/issues/348?

**Comment by GarboMuffin** [comment] 2023-08-28 19:03
Merging into https://github.com/TurboWarp/extensions/issues/930

**Closed by GarboMuffin** 2023-08-28 19:03 UTC
