### ISSUE TITLE
How to make empty defaultValue for STRING argument?

### ISSUE THREAD

**Issue by TrueFantom** [TurboWarp/extensions#51] opened 2022-11-30 16:47 UTC
I wanted to make default argument value look like standard in Scratch 3:
![Screenshot_136](https://user-images.githubusercontent.com/116278271/204847439-85cafa4b-b0fe-4013-8bc2-af1142e7275a.png)
At first I tried to do it like this:
![Screenshot_137](https://user-images.githubusercontent.com/116278271/204848399-ecf40aaf-5cb9-4c2c-9f06-c9e9ea16a0af.png)
But instead of empty value there was undefined
![Screenshot_138](https://user-images.githubusercontent.com/116278271/204849887-d8b12722-04f7-4187-b279-8528d71b09b0.png)
Next I used null
![Screenshot_140](https://user-images.githubusercontent.com/116278271/204852074-d41f4aa5-5d03-40fc-9406-17d037a80503.png)
In this case blocks altogether was disappeared
![Screenshot_141](https://user-images.githubusercontent.com/116278271/204853430-0409a707-8710-444e-b1ba-e8de8f733f49.png)
'\0' and '\u0000' don't work either
![Screenshot_142](https://user-images.githubusercontent.com/116278271/204854100-20dfd88c-14f2-4bf3-82e2-687088a183ea.png)
With their use the 2nd argument of the block was broken, and subsequent blocks disappear
![Screenshot_135](https://user-images.githubusercontent.com/116278271/204854897-c0e56600-f823-49b4-b11f-0e2ed33f5688.png)
I really don't know what to do and would be glad if someone would help me. I am grateful in advance.

(I don't know English so well, so there may be mistakes in this text. If is true I'm sorry)

**Comment by GarboMuffin** [comment] 2022-11-30 16:50
Currently broken, known bug

**Comment by Fantom-408** [comment] 2022-11-30 16:56
Thanks for the answer) I hope this will be fixed soon.

**Comment by Fantom-408** [comment] 2022-11-30 17:01
I do not know whether to close the discussion... I got the answer, but the problem is not solved.

**Comment by Fantom-408** [comment] 2022-11-30 17:18
Ok, thanks)

**Closed** 2022-12-03 18:11 UTC
Labels: bug

**Comment by GarboMuffin** [comment] 2022-12-03 21:46
This will be fixed in the next update

**Comment by TrueFantom** [comment] 2022-12-04 06:37
Glad to hear it)

**Comment by TrueFantom** [comment] 2022-12-09 11:22
Thank you very much, it works)
![Screenshot_155](https://user-images.githubusercontent.com/116278271/206691568-e98a7572-7879-42f5-a13b-b6dfa453913e.png)
